# image will be published to ghcr.io/<user>/<name>
name: xps17-fedora
# description will be included in the image's metadata
description: Personal Laptop ISO

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
       - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
       - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
       - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # command line utilities
      - fish
      - starship
      - tldr
      - btop
      - bolt
      - mesa-vulkan-drivers
      - mesa-libGL
      - nvidia-settings
      - rclone
      - tlp
      - tlp-rdw
      # KVM/QEMU *********************
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - overlayfs-tools
      - qemu-kvm
      - virt-manager
      - virt-viewer
      - guestfs-tools
      - python3-libguestfs
      - virt-top
      - swtpm
      #***********
      - profile-sync-daemon
      - samba
      - freerdp
      - irqbalance
    remove:
      - rom-properties
      - wallpaper-engine-kde-plugin
      - steamdeck-dsp
      - steamdeck-gnome-presets
      - steamdeck-kde-presets-desktop
      - steam_notif_daemon
      - jupiter-fan-control
      - jupiter-hw-support-btrfs
      - jupiter-sd-mounting-btrfs
      - extest
      - ryzenadj
      - sdgyrodsu


  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.github.IsmaelMartinez.teams_for_linux
        - com.visualstudio.code
        - org.gnome.FontManager
        - org.remmina.Remmina
        - sh.cider.Cider
        - io.github.dvlv.boxbuddyrs #box buddy
        - org.freedesktop.Platform.ffmpeg-full
        - app/io.podman_desktop.PodmanDesktop/x86_64/stable
        - app/org.videolan.VLC/x86_64/stable
      # remove:
      # # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: systemd
    # this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled::
        - smb.service
        - nmb.service
        - libvirtd.service
    user:
      enabled:
        - psd.service # TODO: copy service description files to the repo


  - type: akmods
    base: asus # if not specified, classic "main" base is used by default
    install:
      - openrazer
      - openrgb
      - winesync
      - xpadneo
      - xone

  - type: bling
    install:
    - 1password # install 1Password (stable) and `op` CLI tool
    - dconf-update-service # a service unit that updates the dconf db on boot
    - gnome-vrr # enables gnome-vrr for your image

  - type: gnome-extensions
    install:
      - Blur my Shell
      - AppIndicator and KStatusNotifierItem Support
      - Bluetooth Quick Connect
      - Dash to Dock 
      - Forge 
      - Just Perfection
      - Space Bar 
      - System Monitor
      - User Themes
    uninstall:
      - GSConnect # Uninstall step here should be used only for the extensions
      - gnome-shell-extension-caribou-blocker
      - gnome-shell-extension-compiz-windows-effect
      - gnome-shell-extension-hanabi
      - gnome-shell-extension-hotedge