# image will be published to ghcr.io/<user>/<name>
name: xps17-fedora
# description will be included in the image's metadata
description: Personal Laptop ISO

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
       - https://downloads.1password.com/linux/rpm/stable/x86_64
       - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
       - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
       - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    keys:
       - https://downloads.1password.com/linux/keys/1password.asc
    install:
      # command line utilities
      - fish
      - starship
      - tldr
      - btop
      - akmod-nvidia
      - bolt
      - mesa-vulkan-drivers
      - mesa-libGL
      - nvidia-settings
      - rclone
      - tlp
      - tlp-rdw
      # KVM/QEMU *********************
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - overlayfs-tools
      - qemu-kvm
      - virt-manager
      - virt-viewer
      - guestfs-tools
      - python3-libguestfs
      - virt-top
      #***********
      - profile-sync-daemon
      - samba
      - 1password #TODO figure out how to add repo and key
      - freerdp
      - irqbalance
      - pipewire
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.github.IsmaelMartinez.teams_for_linux
        - com.visualstudio.code
        - org.gnome.FontManager
        - org.remmina.Remmina
        - sh.cider.Cider
        - io.github.dvlv.boxbuddyrs #box buddy
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: systemd
    # this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled::
        - smb.service
        - nmb.service
        - libvirtd.service
    user:
      enabled:
        - psd.service # TODO: copy service description files to the repo


  - type: akmods
    base: asus # if not specified, classic "main" base is used by default
    install:
      - nvidia
      - openrgb
      - v4l2loopback
      - winesync

  - type: bling
    install:
    - ublue-update # https://github.com/ublue-os/ublue-update
    - 1password # install 1Password (stable) and `op` CLI tool
    - dconf-update-service # a service unit that updates the dconf db on boot
    - gnome-vrr # enables gnome-vrr for your image